### ISSUE TITLE
Using magento-cache-cleaner

### ISSUE THREAD

**Issue by sebastian-ehrling** [davidalger/warden#180]
Sometimes when using magento cache cleaner, I get the following error if i save a file in my editor.
Any idea?

13:40:12 Cleaning cache type(s) layout full_page
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/var/www/html/vendor/mycompany/module-app-info/view/frontend/layout/.mutagen-temporary-cross-device-rename0'
    at Object.lstatSync (fs.js:845:3)
    at xi (/home/www-data/.composer/vendor/mage2tv/magento-cache-clean/bin/cache-clean.js:343:167)
    at d (/home/www-data/.composer/vendor/mage2tv/magento-cache-clean/bin/cache-clean.js:347:73)
    at FSWatcher.<anonymous> (/home/www-data/.composer/vendor/mage2tv/magento-cache-clean/bin/cache-clean.js:346:174)
    at FSWatcher.emit (events.js:198:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)

Cache Cleaner:
https://github.com/mage2tv/magento-cache-clean

**Comment by Vinai** [comment]
Please open an issue on https://github.com/mage2tv/magento-cache-clean - I'll take care of that one.

**Comment by sebastian-ehrling** [comment]
@Vinai thx!
