### ISSUE TITLE
Integration tests fail after clean install

### ISSUE THREAD

**Issue by jlaughton87** [davidalger/warden#386]
Hi,

I have a clean install of Magento working on my machine using docs: https://docs.warden.dev/environments/magento2.html

Everything appears to be working fine until i try and run an integration test.

After following docs: https://docs.warden.dev/configuration/magento2-testing.html#running-integration-tests and running `vendor/bin/phpunit -c $(pwd)/dev/tests/integration/phpunit.xml ` in warden shell Im receiving the following error logs:
```
Exception: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

In InstallCommand.php line 274:

  [InvalidArgumentException]
  Parameter validation failed


Exception trace:
  at /var/www/html/setup/src/Magento/Setup/Console/Command/InstallCommand.php:274
 Magento\Setup\Console\Command\InstallCommand->initialize() at /var/www/html/vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23

setup:install [--backend-frontname BACKEND-FRONTNAME] [--enable-debug-logging ENABLE-DEBUG-LOGGING] [--enable-syslog-logging ENABLE-SYSLOG-LOGGING] [--remote-storage-driver REMOTE-STORAGE-DRIVER] [--remote-storage-prefix REMOTE-STORAGE-PREFIX] [--remote-storage-bucket REMOTE-STORAGE-BUCKET] [--remote-storage-region REMOTE-STORAGE-REGION] [--remote-storage-key REMOTE-STORAGE-KEY] [--remote-storage-secret REMOTE-STORAGE-SECRET] [--consumers-wait-for-messages CONSUMERS-WAIT-FOR-MESSAGES] [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--db-ssl-key DB-SSL-KEY] [--db-ssl-cert DB-SSL-CERT] [--db-ssl-ca DB-SSL-CA] [--db-ssl-verify] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retries SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETRIES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--cache-backend-redis-compress-data CACHE-BACKEND-REDIS-COMPRESS-DATA] [--cache-backend-redis-compression-lib CACHE-BACKEND-REDIS-COMPRESSION-LIB] [--cache-id-prefix CACHE-ID-PREFIX] [--allow-parallel-generation] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-compression-lib PAGE-CACHE-REDIS-COMPRESSION-LIB] [--page-cache-id-prefix PAGE-CACHE-ID-PREFIX] [--lock-provider LOCK-PROVIDER] [--lock-db-prefix LOCK-DB-PREFIX] [--lock-zookeeper-host LOCK-ZOOKEEPER-HOST] [--lock-zookeeper-path LOCK-ZOOKEEPER-PATH] [--lock-file-path LOCK-FILE-PATH] [--document-root-is-pub DOCUMENT-ROOT-IS-PUB] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user [ADMIN-USER]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--admin-firstname [ADMIN-FIRSTNAME]] [--admin-lastname [ADMIN-LASTNAME]] [--search-engine SEARCH-ENGINE] [--elasticsearch-host ELASTICSEARCH-HOST] [--elasticsearch-port ELASTICSEARCH-PORT] [--elasticsearch-enable-auth ELASTICSEARCH-ENABLE-AUTH] [--elasticsearch-username ELASTICSEARCH-USERNAME] [--elasticsearch-password ELASTICSEARCH-PASSWORD] [--elasticsearch-index-prefix ELASTICSEARCH-INDEX-PREFIX] [--elasticsearch-timeout ELASTICSEARCH-TIMEOUT] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]
 in /var/www/html/vendor/magento/framework/Shell.php:63
Stack trace:
#0 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Application.php(525): Magento\Framework\Shell->execute()
#1 /var/www/html/dev/tests/integration/framework/bootstrap.php(89): Magento\TestFramework\Application->install()
#2 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(56): include_once('/var/www/html/d...')
#3 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(44): PHPUnit\Util\FileLoader::load()
#4 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(552): PHPUnit\Util\FileLoader::checkAndLoad()
#5 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(360): PHPUnit\TextUI\Command->handleBootstrap()
#6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(76): PHPUnit\TextUI\Command->handleArguments()
#7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(68): PHPUnit\TextUI\Command->run()
#8 /var/www/html/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#9 {main}

Next Magento\Framework\Exception\LocalizedException: Command returned non-zero exit code:
`/usr/bin/php -f '/var/www/html/bin/magento' setup:install -vvv --db-host='tmp-mysql' --db-user='root' --db-password='magento' --db-name='magento_integration_tests' --backend-frontname='backend' --search-engine='elasticsearch7' --elasticsearch-host='elasticsearch' --elasticsearch-port='9200' --admin-user='user' --admin-password='password1' --admin-email='admin@example.com' --admin-firstname='firstname' --admin-lastname='lastname' --amqp-host='rabbitmq' --amqp-port='5672' --amqp-user='guest' --amqp-password='guest' --session-save='redis' --session-save-redis-host='redis' --session-save-redis-port='6379' --session-save-redis-db='2' --session-save-redis-max-concurrency='20' --cache-backend='redis' --cache-backend-redis-server='redis' --cache-backend-redis-db='0' --cache-backend-redis-port='6379' --page-cache='redis' --page-cache-redis-server='redis' --page-cache-redis-db='1' --page-cache-redis-port='6379' --magento-init-params='MAGE_DIRS[etc][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/etc&MAGE_DIRS[var][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var&MAGE_DIRS[var_export][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var/export&MAGE_DIRS[media][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/pub/media&MAGE_DIRS[static][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/pub/static&MAGE_DIRS[view_preprocessed][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var/view_preprocessed/pub/static&MAGE_DIRS[code][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/generated/code&MAGE_DIRS[cache][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var/cache&MAGE_DIRS[log][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var/log&MAGE_DIRS[session][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var/session&MAGE_DIRS[tmp][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var/tmp&MAGE_DIRS[upload][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var/upload&MAGE_DIRS[pub][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/pub&MAGE_DIRS[import_export][path]=/var/www/html/dev/tests/integration/tmp/sandbox-0-577e01bf567b3b9c416bf953f1c143639686b4fe6076b217ca0ed321f16372af/var&MAGE_MODE=developer' 2>&1` in /var/www/html/vendor/magento/framework/Shell.php:64
Stack trace:
#0 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Application.php(525): Magento\Framework\Shell->execute()
#1 /var/www/html/dev/tests/integration/framework/bootstrap.php(89): Magento\TestFramework\Application->install()
#2 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(56): include_once('/var/www/html/d...')
#3 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(44): PHPUnit\Util\FileLoader::load()
#4 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(552): PHPUnit\Util\FileLoader::checkAndLoad()
#5 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(360): PHPUnit\TextUI\Command->handleBootstrap()
#6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(76): PHPUnit\TextUI\Command->handleArguments()
#7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(68): PHPUnit\TextUI\Command->run()
#8 /var/www/html/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#9 {main}

=== Memory Usage System Stats ===
Memory usage (OS):      42.02M (420.23% of 10.00M reported by PHP, 0.51% of configured 8192.00M limit)
Estimated memory leak:  32.02M (76.20% of used memory)
```

I can find anything which would cause `php_network_getaddresses: getaddrinfo failed: Name or service not known` and it looks like memory usage is way too high. 

Any help would be appreciated,

Cheers,
Jamie

**Comment by sprankhub** [comment]
Please double-check that you have the test database enabled in your `.env` file:

    WARDEN_TEST_DB=1

Most probably, it is not enabled for you. After enabling it, run `warden env up` again and retry.

**Comment by alexandrosk** [comment]
I had the same issue, turns out I had 
`WARDEN_TEST_DB=0` by the end of .env file so it was overwritting it please check again @MagePsycho
