### ISSUE TITLE
Issues With Magepack Generate

### ISSUE THREAD

**Issue by ryan-copeland** [davidalger/warden#404]
I am are trying to use the magepack container by following the guide in the PR below:

https://github.com/davidalger/warden/pull/138

When attempting to run the `magepack generate` command I am getting the following error message returned:

```
warden env exec magepack generate \
>     --cms-url="https://warden.test/" \
>     --category-url="https://warden.test/category-url/" \
>     --product-url="https://warden.test/product-url/"
ℹ Collecting bundle modules in the browser.                                                                         08:29:49
ℹ Collecting modules for bundle "category".                                                                         08:29:49
✔ Finished collecting modules for bundle "category".                                                                08:29:57
ℹ Collecting modules for bundle "cms".                                                                              08:29:57
✔ Finished collecting modules for bundle "cms".                                                                     08:30:04
ℹ Collecting modules for bundle "product".                                                                          08:30:04
✔ Finished collecting modules for bundle "product".                                                                 08:30:14
ℹ Collecting modules for bundle "checkout".                                                                         08:30:14

 ERROR  Navigation timeout of 30000 ms exceeded                                                                     08:30:48

  at /usr/lib/node_modules/magepack/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  at async FrameManager.waitForFrameNavigation (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/FrameManager.js:139:19)
  at async Frame.waitForNavigation (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/FrameManager.js:414:12)
  at async Page.waitForNavigation (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js:692:12)
  at async Promise.all (index 0)
  at async Object.checkout (/usr/lib/node_modules/magepack/lib/generate/collector/checkout.js:75:5)
  at async module.exports (/usr/lib/node_modules/magepack/lib/generate.js:24:13)
  -- ASYNC --
  at Frame.<anonymous> (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:111:15)
  at Page.waitForNavigation (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/Page.js:692:49)
  at Page.<anonymous> (/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/helper.js:112:23)
  at Object.checkout (/usr/lib/node_modules/magepack/lib/generate/collector/checkout.js:76:14)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async module.exports (/usr/lib/node_modules/magepack/lib/generate.js:24:13)
```

Has anyone else experienced this issue before?

**Comment by ryan-copeland** [comment]
Seems to be timeout problem. I found the below:

https://github.com/magesuite/magepack/issues/11

Can anyone point me in the right direction as to how we can extend the timeouts?

**Comment by ryan-copeland** [comment]
Ok I've found the file that I need to update. See below:

`/usr/lib/node_modules/magepack/node_modules/puppeteer/lib/TimeoutSettings.js`

Problem is that I don't have write permissions to do so and sudo doesn't seem to work either. 

Could anyone point me in the right direction for applying updates to this file?

**Comment by davidalger** [comment]
@ryan-copeland I can't speak to the error itself, but if you need root in the `magepack` container to edit soemthing for testing purposes, you enter the container as root via `warden env exec -u 0 magepack sh` avoiding the need to use `sudo`

**Comment by mrtuvn** [comment]
Maybe not related but can i access elastic container with same command mentioned? (Root)
One more question. I dont see magento mention user authenticate from elastic.! What user role allowed

**Comment by celorodovalho** [comment]
Try this one:

```
warden env exec -u 0 magepack sed -i -e "s#30000#60000#g" /usr/lib/node_modules/magepack/node_modules/puppeteer/lib/TimeoutSettings.js
```

It does the trick
